In [1]:
# for loop using factorial

In [4]:
num = int(input("Enter a number :- "))
factorial = 1
for i in range(1, num+1):
  factorial = factorial * i

print("The factorial of no is", factorial)

Enter a number :- 6
The factorial of no is 720

In [5]:
# Numpy - numerical python

In [6]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [7]:
import numpy as np

In [8]:
a = [1,2,3,4,5,6]

In [9]:
b = np.array(a)

In [10]:
type(a)

list

In [11]:
type(b)

numpy.ndarray

In [12]:
print(b)

[1 2 3 4 5 6]

In [13]:
b

array([1, 2, 3, 4, 5, 6])

In [14]:
#2D array

In [15]:
c = np.array([[1,2,3], [4,5,6]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# 3D array

In [18]:
d = np.array([[[1,2], [3,4]],
             [[4,5], [6,7]]])

In [19]:
d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [20]:
# attributed

In [21]:
b.ndim

1

In [22]:
c.ndim

2

In [23]:
d.ndim

3

In [24]:
d.shape

(2, 2, 2)

In [25]:
c.shape

(2, 3)

In [26]:
c.size

6

In [27]:
c.dtype

dtype('int64')

In [28]:
# int whole no - int8, int16, int32, int64
# positive int - unsigned int - np.uint16,32
# float - decimal - float 16,32,64
# boolian - True/False - np.bool_
# string - np.str_ ex - "tushar"
# object - np.object_ ex - "Admin@123"

In [29]:
# method - .methodname()

In [30]:
np.random.rand()  # 0 to 1

0.40111842672622666

In [32]:
np.random.rand(5)

array([0.07131284, 0.60543277, 0.57555676, 0.96460652, 0.92158406])

In [33]:
np.random.rand(2,3)

array([[0.21566803, 0.44954268, 0.46328479],
       [0.83980855, 0.14107252, 0.84417557]])

In [34]:
np.random.randn(5)

array([-0.19150477, -0.98327069,  1.07029148,  0.4680344 ,  0.09218214])

In [39]:
np.random.randint(1,7)

6

In [40]:
np.mean(c)

np.float64(3.5)

In [41]:
np.max(c)

np.int64(6)

In [42]:
np.min(c)

np.int64(1)

In [43]:
np.std(c)

np.float64(1.707825127659933)

In [44]:
np.var(c)

np.float64(2.9166666666666665)

In [45]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Pandas - panel data
- build on numpy library
- deals with Series and DataFrame

In [47]:
import numpy as np
import pandas as pd

In [48]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [50]:
num = [45,84,56,95]

In [51]:
pd.Series(num)

0    45
1    84
2    56
3    95
dtype: int64

In [52]:
index_name = ["row1", "row2", "row3", "row4"]

In [53]:
pd.Series(num, index = index_name, name= "Column1")

row1    45
row2    84
row3    56
row4    95
Name: Column1, dtype: int64

In [54]:
data = {"name": ["pradip", "gayatri", "pratiksha"],
        "Age": [18,10,5],
        "City": ["Dubai", "America", "Amazon"]}

In [55]:
pd.Series(data)

name    [pradip, gayatri, pratiksha]
Age                      [18, 10, 5]
City        [Dubai, America, Amazon]
dtype: object

In [58]:
df = pd.DataFrame(data, index=['r1', 'r2','r3'])

In [59]:
df

         name  Age     City
r1     pradip   18    Dubai
r2    gayatri   10  America
r3  pratiksha    5   Amazon

In [60]:
df.shape

(3, 3)

In [61]:
df.size

9

In [63]:
df.dtypes

name    object
Age      int64
City    object
dtype: object

In [64]:
df.ndim

2

In [65]:
df.columns

Index(['name', 'Age', 'City'], dtype='object')

In [66]:
df.index

Index(['r1', 'r2', 'r3'], dtype='object')

In [67]:
df.values

array([['pradip', 18, 'Dubai'],
       ['gayatri', 10, 'America'],
       ['pratiksha', 5, 'Amazon']], dtype=object)