In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [4]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [6]:
df.head() #top 5

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [7]:
df.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0

In [8]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [9]:
df.tail(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [11]:
import seaborn as sns

In [12]:
df1 = sns.load_dataset("titanic")

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [15]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [16]:
df1.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [17]:
df1.describe(include="all")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df1.sample(4)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
66,1,2,female,29.0,0,0,10.5000,S,Second,woman,False,F,Southampton,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
661,0,3,male,40.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
86,0,3,male,16.0,1,3,34.3750,S,Third,man,True,NaN,Southampton,no,False

In [19]:
df1['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [20]:
df1[["age", "sex"]]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
..    ...     ...
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [23]:
# imp (iloc - index location) when we have numbers in location

In [24]:
df1.iloc[45]

survived                 0
pclass                   3
sex                   male
age                    NaN
sibsp                    0
parch                    0
fare                  8.05
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 45, dtype: object

In [26]:
df1.loc[4]  # when rows has names

survived                 0
pclass                   3
sex                   male
age                   35.0
sibsp                    0
parch                    0
fare                  8.05
embarked                 S
class                Third
who                    man
adult_male            True
deck                   NaN
embark_town    Southampton
alive                   no
alone                 True
Name: 4, dtype: object

In [28]:
df1['age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [29]:
df1[df1['age']<5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
63,0,3,male,4.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
171,0,3,male,4.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
374,0,3,female,3.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
530,1,2,female,2.00,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
618,1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
642,0,3,female,2.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
750,1,2,female,4.00,1,1,23.0000,S,Second,child,False,NaN,Southampton,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
824,0,3,male,2.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [30]:
df1[df1['age']==1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
164,0,3,male,1.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
172,1,3,female,1.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
183,1,2,male,1.0,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
381,1,3,female,1.0,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
386,0,3,male,1.0,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
788,1,3,male,1.0,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
827,1,2,male,1.0,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False

In [31]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [33]:
df5 = df.sort_values("housing_median_age")

In [34]:
df5.head(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.875,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0

In [35]:
df5.reset_index(0)

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2,2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
3,2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
4,1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...,...
2995,26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
2996,36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2997,2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2998,2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2999,2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

In [37]:
df5.reset_index().head(2)

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.875,141700.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0

In [38]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [41]:
df1['new fare'] = df1['fare'] * 2   # new column add

In [42]:
df1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,14.5000
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,142.5666
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,15.8500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,106.2000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,16.1000

In [44]:
df1.drop("who", axis = 1)   # axis 1 for column,  0 for row

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone,new fare
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False,14.5000
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False,142.5666
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,15.8500
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False,106.2000
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True,16.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True,NaN,Southampton,no,True,26.0000
887,1,1,female,19.0,0,0,30.0000,S,First,False,B,Southampton,yes,True,60.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,False,NaN,Southampton,no,False,46.9000
889,1,1,male,26.0,0,0,30.0000,C,First,True,C,Cherbourg,yes,True,60.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,True,NaN,Queenstown,no,True,15.5000

In [45]:
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new fare
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,14.5000
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,142.5666
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,15.8500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,106.2000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,16.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,26.0000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,60.0000
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,46.9000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,60.0000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,15.5000

In [51]:
df1.drop("parch", axis = 1, inplace=True)

In [52]:
df1

,survived,pclass,sex,age,sibsp,fare,embarked,class,adult_male,deck,embark_town,alive,alone,new fare
0,0,3,male,22.0,1,7.2500,S,Third,True,NaN,Southampton,no,False,14.5000
1,1,1,female,38.0,1,71.2833,C,First,False,C,Cherbourg,yes,False,142.5666
2,1,3,female,26.0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,15.8500
3,1,1,female,35.0,1,53.1000,S,First,False,C,Southampton,yes,False,106.2000
4,0,3,male,35.0,0,8.0500,S,Third,True,NaN,Southampton,no,True,16.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,13.0000,S,Second,True,NaN,Southampton,no,True,26.0000
887,1,1,female,19.0,0,30.0000,S,First,False,B,Southampton,yes,True,60.0000
888,0,3,female,NaN,1,23.4500,S,Third,False,NaN,Southampton,no,False,46.9000
889,1,1,male,26.0,0,30.0000,C,First,True,C,Cherbourg,yes,True,60.0000
890,0,3,male,32.0,0,7.7500,Q,Third,True,NaN,Queenstown,no,True,15.5000

In [53]:
df1.rename(columns={"sex":"gender"})

,survived,pclass,gender,age,sibsp,fare,embarked,class,adult_male,deck,embark_town,alive,alone,new fare
0,0,3,male,22.0,1,7.2500,S,Third,True,NaN,Southampton,no,False,14.5000
1,1,1,female,38.0,1,71.2833,C,First,False,C,Cherbourg,yes,False,142.5666
2,1,3,female,26.0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,15.8500
3,1,1,female,35.0,1,53.1000,S,First,False,C,Southampton,yes,False,106.2000
4,0,3,male,35.0,0,8.0500,S,Third,True,NaN,Southampton,no,True,16.1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,13.0000,S,Second,True,NaN,Southampton,no,True,26.0000
887,1,1,female,19.0,0,30.0000,S,First,False,B,Southampton,yes,True,60.0000
888,0,3,female,NaN,1,23.4500,S,Third,False,NaN,Southampton,no,False,46.9000
889,1,1,male,26.0,0,30.0000,C,First,True,C,Cherbourg,yes,True,60.0000
890,0,3,male,32.0,0,7.7500,Q,Third,True,NaN,Queenstown,no,True,15.5000

In [54]:
df1.isnull()

,survived,pclass,sex,age,sibsp,fare,embarked,class,adult_male,deck,embark_town,alive,alone,new fare
0,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,True,False,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,True,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,True,False,False,False,False

In [56]:
df1.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
fare             0
embarked         2
class            0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
new fare         0
dtype: int64

In [57]:
df1.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
fare           891
embarked       889
class          891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
new fare       891
dtype: int64

In [58]:
df1['embarked'].fillna("Tushar")

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: embarked, Length: 891, dtype: object

In [59]:
df1.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
fare             0
embarked         2
class            0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
new fare         0
dtype: int64

In [60]:
df1.dropna(inplace=True)

In [61]:
df1.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
fare           0
embarked       0
class          0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
new fare       0
dtype: int64

In [62]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 182 entries, 1 to 889
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     182 non-null    int64
 1   pclass       182 non-null    int64
 2   sex          182 non-null    object
 3   age          182 non-null    float64
 4   sibsp        182 non-null    int64
 5   fare         182 non-null    float64
 6   embarked     182 non-null    object
 7   class        182 non-null    category
 8   adult_male   182 non-null    bool
 9   deck         182 non-null    category
 10  embark_town  182 non-null    object
 11  alive        182 non-null    object
 12  alone        182 non-null    bool
 13  new fare     182 non-null    float64
dtypes: bool(2), category(2), float64(3), int64(3), object(4)
memory usage: 16.8+ KB

In [63]:
df1['age'].sum()

np.float64(6483.42)

In [64]:
df1['age'].mean()

np.float64(35.62318681318681)

In [65]:
df1['age'].median()

36.0

In [66]:
# IMP

In [67]:
df1['sex'].unique()

array(['female', 'male'], dtype=object)

In [69]:
new_df = df1['sex'].value_counts()

In [70]:
new_df

sex
male      94
female    88
Name: count, dtype: int64

In [71]:
new_df.index

Index(['male', 'female'], dtype='object', name='sex')

In [72]:
new_df.values

array([94, 88])

In [73]:
df1.groupby("sex")["survived"].mean()*100

sex
female    93.181818
male      43.617021
Name: survived, dtype: float64

In [74]:
df1.groupby(["sex", "pclass"])["survived"].mean()*100

sex     pclass
female  1         95.945946
        2         88.888889
        3         60.000000
male    1         42.168675
        2         66.666667
        3         40.000000
Name: survived, dtype: float64