In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df = pd.read_excel("/content/DataDNA Dataset Challenge - E-commerce Dataset - November 2025.xlsx")

In [33]:
df.head()

,event_id,event_type,event_date,customer_id,product_id,country,latitude,longitude,region,channel,...,unit_price_local,discount_code,discount_local,tax_local,net_revenue_local,fx_rate_to_usd,net_revenue_usd,is_refunded,refund_datetime,refund_reason
0,DB4F1A096586,order,2024-12-09 00:11:27,CUST0001946,PROD0083,United States,39.8283,-98.5795,NaN,Website,...,36.70,NaN,0.0,0.00,110.10,1.00,110.10,False,NaT,NaN
1,3550A69EEA36,order,2025-08-11 21:31:03,CUST0003776,PROD0049,Australia,-25.2744,133.7751,APAC,Website,...,19.70,NaN,0.0,9.85,108.35,0.66,71.51,False,NaT,NaN
2,0C3CAE65E90C,order,2025-09-30 15:39:28,CUST0001105,PROD0075,Canada,56.1304,-106.3468,NaN,Website,...,20.12,NaN,0.0,1.01,21.13,1.00,21.13,False,NaT,NaN
3,7DDC83355865,invoice,2024-09-26 04:13:11,CUST0003164,PROD0017,United States,39.8283,-98.5795,NaN,Partner,...,19.00,NaN,0.0,0.00,190.00,1.00,190.00,False,NaT,NaN
4,DAE0B37D8815,order,2024-06-23 16:03:04,CUST0003410,PROD0099,United States,39.8283,-98.5795,NaN,Website,...,29.38,NaN,0.0,0.00,88.14,1.00,88.14,False,NaT,NaN

In [34]:
df.columns

Index(['event_id', 'event_type', 'event_date', 'customer_id', 'product_id',
       'country', 'latitude', 'longitude', 'region', 'channel',
       'payment_method', 'currency', 'quantity', 'unit_price_local',
       'discount_code', 'discount_local', 'tax_local', 'net_revenue_local',
       'fx_rate_to_usd', 'net_revenue_usd', 'is_refunded', 'refund_datetime',
       'refund_reason'],
      dtype='object')

In [35]:
df.shape

(48000, 23)

In [36]:
df.dtypes

event_id                     object
event_type                   object
event_date           datetime64[ns]
customer_id                  object
product_id                   object
country                      object
latitude                    float64
longitude                   float64
region                       object
channel                      object
payment_method               object
currency                     object
quantity                      int64
unit_price_local            float64
discount_code                object
discount_local              float64
tax_local                   float64
net_revenue_local           float64
fx_rate_to_usd              float64
net_revenue_usd             float64
is_refunded                    bool
refund_datetime      datetime64[ns]
refund_reason                object
dtype: object

In [37]:
df.isnull().sum()

event_id                 0
event_type               0
event_date               0
customer_id              0
product_id               0
country                  0
latitude                 0
longitude                0
region               19579
channel                  0
payment_method           0
currency                 0
quantity                 0
unit_price_local         0
discount_code        31020
discount_local           0
tax_local                0
net_revenue_local        0
fx_rate_to_usd           0
net_revenue_usd          0
is_refunded              0
refund_datetime      46995
refund_reason        46995
dtype: int64

In [38]:
# So the missing region is replacable by unkonwn
# the discount code is missing that may be beacuse they dont get any discount
# so we can replace it by no_discount
# Refund datetime not mention_because the refund datetime and redund reason
# are the products which is not refunded thats why they didn't mention the date and also the reason.

In [39]:
# So lets fill the missing

In [40]:
df['region'] = df['region'].fillna("Unkown")

In [41]:
df['discount_code'] = df['discount_code'].fillna("No_Discount")

In [42]:
df['refund_reason'] = df['refund_reason'].fillna("Not_Refunded")

In [43]:
# verify the missing value

In [44]:
df.isnull().sum()

event_id                 0
event_type               0
event_date               0
customer_id              0
product_id               0
country                  0
latitude                 0
longitude                0
region                   0
channel                  0
payment_method           0
currency                 0
quantity                 0
unit_price_local         0
discount_code            0
discount_local           0
tax_local                0
net_revenue_local        0
fx_rate_to_usd           0
net_revenue_usd          0
is_refunded              0
refund_datetime      46995
refund_reason            0
dtype: int64

In [45]:
# refund_datetime is intentially showing 46995, that mean 46995 orders are not refunded yet.

In [46]:
# Lets find out the object columns

In [47]:
df.select_dtypes(include=["object"]).columns

Index(['event_id', 'event_type', 'customer_id', 'product_id', 'country',
       'region', 'channel', 'payment_method', 'currency', 'discount_code',
       'refund_reason'],
      dtype='object')

In [48]:
cat_col = ['event_id', 'event_type', 'customer_id', 'product_id', 'country',
       'region', 'channel', 'payment_method', 'currency', 'discount_code',
       'refund_reason']

In [49]:
for i in cat_col:
  print(i, " : - ", df[i].unique())
  print("............................")

event_id  : -  ['DB4F1A096586' '3550A69EEA36' '0C3CAE65E90C' ... '31681CA1A687'
 'E5332EABFA60' '64381905AD06']
............................
event_type  : -  ['order' 'invoice']
............................
customer_id  : -  ['CUST0001946' 'CUST0003776' 'CUST0001105' ... 'CUST0001996' 'CUST0001296'
 'CUST0003384']
............................
product_id  : -  ['PROD0083' 'PROD0049' 'PROD0075' 'PROD0017' 'PROD0099' 'PROD0026'
 'PROD0059' 'PROD0100' 'PROD0027' 'PROD0067' 'PROD0047' 'PROD0055'
 'PROD0078' 'PROD0074' 'PROD0076' 'PROD0053' 'PROD0003' 'PROD0033'
 'PROD0020' 'PROD0022' 'PROD0012' 'PROD0087' 'PROD0002' 'PROD0019'
 'PROD0025' 'PROD0029' 'PROD0041' 'PROD0077' 'PROD0023' 'PROD0035'
 'PROD0006' 'PROD0052' 'PROD0089' 'PROD0086' 'PROD0050' 'PROD0046'
 'PROD0072' 'PROD0008' 'PROD0007' 'PROD0080' 'PROD0039' 'PROD0084'
 'PROD0011' 'PROD0062' 'PROD0063' 'PROD0037' 'PROD0095' 'PROD0001'
 'PROD0048' 'PROD0090' 'PROD0042' 'PROD0082' 'PROD0060' 'PROD0073'
 'PROD0038' 'PROD0014' 'PROD0066' 'PROD0054' 'PROD0098' 'PROD0068'
 'PROD0058' 'PROD0051' 'PROD0036' 'PROD0021' 'PROD0061' 'PROD0005'
 'PROD0092' 'PROD0044' 'PROD0004' 'PROD0030' 'PROD0010' 'PROD0040'
 'PROD0064' 'PROD0056' 'PROD0057' 'PROD0088' 'PROD0028' 'PROD0096'
 'PROD0032' 'PROD0081' 'PROD0015' 'PROD0009' 'PROD0070' 'PROD0045'
 'PROD0097' 'PROD0018' 'PROD0101' 'PROD0016' 'PROD0079' 'PROD0094'
 'PROD0043' 'PROD0065' 'PROD0085' 'PROD0034' 'PROD0071' 'PROD0093'
 'PROD0024' 'PROD0069' 'PROD0091' 'PROD0031' 'PROD0013']
............................
country  : -  ['United States' 'Australia' 'Canada' 'Germany' 'Brazil' 'United Kingdom'
 'France' 'Philippines' 'Spain' 'Netherlands']
............................
region  : -  ['Unkown' 'APAC' 'EU' 'LATAM']
............................
channel  : -  ['Website' 'Partner' 'Direct Sales' 'Marketplace' 'Reseller']
............................
payment_method  : -  ['Credit Card' 'Invoice' 'Wire' 'PayPal']
............................
currency  : -  ['USD' 'AUD' 'EUR' 'GBP']
............................
discount_code  : -  ['No_Discount' 'NEWCUSTOMER10' 'EDU10' 'LOYALTY15' 'SAVE5' 'BFCM10'
 'BFCM20' 'WELCOME10' 'STUDENT15' 'SALE15' 'STUDENT20' 'STUDENT10' 'EDU15'
 'EDU20']
............................
refund_reason  : -  ['Not_Refunded' 'Accidental purchase' 'Billing error'
 'Service dissatisfaction' 'Duplicate order']
............................

In [50]:
# Lets do the feature engineering
# Drop the event_id, Customer_id, and product_id

In [51]:
df.drop(columns=['event_id', 'customer_id', 'product_id'], inplace=True)

In [52]:
df.head()

,event_type,event_date,country,latitude,longitude,region,channel,payment_method,currency,quantity,unit_price_local,discount_code,discount_local,tax_local,net_revenue_local,fx_rate_to_usd,net_revenue_usd,is_refunded,refund_datetime,refund_reason
0,order,2024-12-09 00:11:27,United States,39.8283,-98.5795,Unkown,Website,Credit Card,USD,3,36.70,No_Discount,0.0,0.00,110.10,1.00,110.10,False,NaT,Not_Refunded
1,order,2025-08-11 21:31:03,Australia,-25.2744,133.7751,APAC,Website,Invoice,AUD,5,19.70,No_Discount,0.0,9.85,108.35,0.66,71.51,False,NaT,Not_Refunded
2,order,2025-09-30 15:39:28,Canada,56.1304,-106.3468,Unkown,Website,Credit Card,USD,1,20.12,No_Discount,0.0,1.01,21.13,1.00,21.13,False,NaT,Not_Refunded
3,invoice,2024-09-26 04:13:11,United States,39.8283,-98.5795,Unkown,Partner,Credit Card,USD,10,19.00,No_Discount,0.0,0.00,190.00,1.00,190.00,False,NaT,Not_Refunded
4,order,2024-06-23 16:03:04,United States,39.8283,-98.5795,Unkown,Website,Credit Card,USD,3,29.38,No_Discount,0.0,0.00,88.14,1.00,88.14,False,NaT,Not_Refunded

In [53]:
# Lets check the duplicate records

df.duplicated().sum()

np.int64(0)